<a href="https://colab.research.google.com/github/Isaque-BD/FATEC-API-6-SEMESTRE/blob/spike-us-12-c%C3%A1lculo-dec/DEC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Indicadores-continuidade-coletivos-2020-2029

In [ ]:
import requests
import pandas as pd

# Filtrei em ambas a URL o conjunto GUACUI como amostra, seu IdeConjUndConsumidoras = 15394
URL_DEC_REALIZADO = 'https://dadosabertos.aneel.gov.br/api/3/action/datastore_search_sql?sql=SELECT%20*%20FROM%20%224493985c-baea-429c-9df5-3030422c71d7%22%20WHERE%20%22IdeConjUndConsumidoras%22%20IN%20(%2715394%27)'
URL_DEC_LIMITE = 'https://dadosabertos.aneel.gov.br/api/3/action/datastore_search_sql?sql=SELECT%20*%20FROM%20%22fd69e1dd-fd66-4269-b60c-cc0b7eb221b4%22%20WHERE%20%22IdeConjUndConsumidoras%22%20IN%20(%2715394%27)'


# Carrega os dados no dataframe
response_dec_realizado = requests.get(URL_DEC_REALIZADO, timeout=30)
records_dec_realizado = response_dec_realizado.json()['result']['records']
df_dec_realizado = pd.DataFrame(records_dec_realizado)

print(df_dec_realizado.shape)
df_dec_realizado

(1443, 11)

,_id,_full_text,DatGeracaoConjuntoDados,SigAgente,NumCNPJ,IdeConjUndConsumidoras,DscConjUndConsumidoras,SigIndicador,AnoIndice,NumPeriodoIndice,VlrIndiceEnviado
0,1610,'-01':2 '-05':3 '00':12 '15394':7 '2020':10 '2...,2026-01-05,EDP ES,28152650000171,15394,GUACUI,FECINO,2020,3,",00"
1,3740,'-01':2 '-05':3 '00':12 '11':11 '15394':7 '202...,2026-01-05,EDP ES,28152650000171,15394,GUACUI,DECXPC,2020,11,",00"
2,13934,'-01':2 '-05':3 '00':12 '15394':7 '2020':10 '2...,2026-01-05,EDP ES,28152650000171,15394,GUACUI,DECIPC,2020,3,",00"
3,14884,'-01':2 '-05':3 '07':12 '1':11 '15394':7 '2020...,2026-01-05,EDP ES,28152650000171,15394,GUACUI,FECINE,2020,1,",07"
4,15593,'-01':2 '-05':3 '00':12 '11':11 '15394':7 '202...,2026-01-05,EDP ES,28152650000171,15394,GUACUI,FECINO,2020,11,",00"
...,...,...,...,...,...,...,...,...,...,...,...
1438,4519158,'-01':2 '-05':3 '00':12 '15394':7 '2025':10 '2...,2026-01-05,EDP ES,28152650000171,15394,GUACUI,DECINO,2025,4,",00"
1439,4519908,'-01':2 '-05':3 '00':12 '15394':7 '2025':10 '2...,2026-01-05,EDP ES,28152650000171,15394,GUACUI,DECINC,2025,8,",00"
1440,4522011,'-01':2 '-05':3 '05':12 '15394':7 '2025':10 '2...,2026-01-05,EDP ES,28152650000171,15394,GUACUI,DECIP,2025,5,",05"
1441,4520503,'-01':2 '-05':3 '07':12 '10':11 '15394':7 '202...,2026-01-05,EDP ES,28152650000171,15394,GUACUI,DECIP,2025,10,",07"
1442,4520699,'-01':2 '-05':3 '00':12 '15394':7 '2025':10 '2...,2026-01-05,EDP ES,28152650000171,15394,GUACUI,DECINO,2025,3,",00"

In [ ]:
response_dec_limite = requests.get(URL_DEC_LIMITE, timeout=30)
records_dec_limite = response_dec_limite.json()['result']['records']
df_dec_limite = pd.DataFrame(records_dec_limite)

print(df_dec_limite.shape)
df_dec_limite

(31, 10)

,_id,_full_text,DatGeracaoConjuntoDados,SigAgente,NumCNPJ,IdeConjUndConsumidoras,DscConjUndConsumidoras,SigIndicador,AnoLimiteQualidade,VlrLimite
0,1,'-01':2 '-05':3 '00':12 '15394':7 '1990':10 '2...,2026-01-05,EDP ES,28152650000171,15394,GUACUI,FEC,1990,"8,00"
1,138827,'-01':2 '-05':3 '00':12 '14':11 '15394':7 '201...,2026-01-05,EDP ES,28152650000171,15394,GUACUI,DEC,2011,"14,00"
2,138897,'-01':2 '-05':3 '00':12 '14':11 '15394':7 '201...,2026-01-05,EDP ES,28152650000171,15394,GUACUI,FEC,2011,"14,00"
3,157390,'-01':2 '-05':3 '00':12 '13':11 '15394':7 '201...,2026-01-05,EDP ES,28152650000171,15394,GUACUI,FEC,2012,"13,00"
4,157509,'-01':2 '-05':3 '00':12 '14':11 '15394':7 '201...,2026-01-05,EDP ES,28152650000171,15394,GUACUI,DEC,2012,"14,00"
5,159634,'-01':2 '-05':3 '00':12 '13':11 '15394':7 '201...,2026-01-05,EDP ES,28152650000171,15394,GUACUI,FEC,2013,"13,00"
6,159788,'-01':2 '-05':3 '00':12 '13':11 '15394':7 '201...,2026-01-05,EDP ES,28152650000171,15394,GUACUI,DEC,2013,"13,00"
7,172025,'-01':2 '-05':3 '00':12 '13':11 '15394':7 '201...,2026-01-05,EDP ES,28152650000171,15394,GUACUI,FEC,2014,"13,00"
8,177522,'-01':2 '-05':3 '00':12 '13':11 '15394':7 '201...,2026-01-05,EDP ES,28152650000171,15394,GUACUI,DEC,2015,"13,00"
9,172233,'-01':2 '-05':3 '00':12 '13':11 '15394':7 '201...,2026-01-05,EDP ES,28152650000171,15394,GUACUI,DEC,2014,"13,00"
10,186531,'-01':2 '-05':3 '00':12 '11':11 '15394':7 '201...,2026-01-05,EDP ES,28152650000171,15394,GUACUI,FEC,2016,"11,00"
11,177496,'-01':2 '-05':3 '00':12 '12':11 '15394':7 '201...,2026-01-05,EDP ES,28152650000171,15394,GUACUI,FEC,2015,"12,00"
12,186414,'-01':2 '-05':3 '00':12 '13':11 '15394':7 '201...,2026-01-05,EDP ES,28152650000171,15394,GUACUI,DEC,2016,"13,00"
13,191499,'-01':2 '-05':3 '00':12 '13':11 '15394':7 '201...,2026-01-05,EDP ES,28152650000171,15394,GUACUI,DEC,2017,"13,00"
14,191525,'-01':2 '-05':3 '00':12 '11':11 '15394':7 '201...,2026-01-05,EDP ES,28152650000171,15394,GUACUI,FEC,2017,"11,00"
15,199700,'-01':2 '-05':3 '00':12 '13':11 '15394':7 '201...,2026-01-05,EDP ES,28152650000171,15394,GUACUI,DEC,2018,"13,00"
16,202566,'-01':2 '-05':3 '00':12 '13':11 '15394':7 '201...,2026-01-05,EDP ES,28152650000171,15394,GUACUI,DEC,2019,"13,00"
17,199686,'-01':2 '-05':3 '00':12 '10':11 '15394':7 '201...,2026-01-05,EDP ES,28152650000171,15394,GUACUI,FEC,2018,"10,00"
18,207982,'-01':2 '-05':3 '00':12 '10':11 '15394':7 '202...,2026-01-05,EDP ES,28152650000171,15394,GUACUI,FEC,2020,"10,00"
19,202514,'-01':2 '-05':3 '00':12 '10':11 '15394':7 '201...,2026-01-05,EDP ES,28152650000171,15394,GUACUI,FEC,2019,"10,00"
20,208112,'-01':2 '-05':3 '00':12 '13':11 '15394':7 '202...,2026-01-05,EDP ES,28152650000171,15394,GUACUI,DEC,2020,"13,00"
21,219879,'-01':2 '-05':3 '00':12 '13':11 '15394':7 '202...,2026-01-05,EDP ES,28152650000171,15394,GUACUI,DEC,2021,"13,00"
22,219928,'-01':2 '-05':3 '00':12 '15394':7 '2021':10 '2...,2026-01-05,EDP ES,28152650000171,15394,GUACUI,FEC,2021,"9,00"
23,221661,'-01':2 '-05':3 '00':12 '15394':7 '2022':10 '2...,2026-01-05,EDP ES,28152650000171,15394,GUACUI,FEC,2022,"9,00"
24,233782,'-01':2 '-05':3 '00':12 '15394':7 '2024':10 '2...,2026-01-05,EDP ES,28152650000171,15394,GUACUI,FEC,2024,"8,00"
25,232671,'-01':2 '-05':3 '00':12 '12':11 '15394':7 '202...,2026-01-05,EDP ES,28152650000171,15394,GUACUI,DEC,2023,"12,00"
26,232953,'-01':2 '-05':3 '00':12 '15394':7 '2023':10 '2...,2026-01-05,EDP ES,28152650000171,15394,GUACUI,FEC,2023,"9,00"
27,221721,'-01':2 '-05':3 '00':12 '12':11 '15394':7 '202...,2026-01-05,EDP ES,28152650000171,15394,GUACUI,DEC,2022,"12,00"
28,234046,'-01':2 '-05':3 '00':12 '12':11 '15394':7 '202...,2026-01-05,EDP ES,28152650000171,15394,GUACUI,DEC,2024,"12,00"
29,245063,'-01':2 '-05':3 '00':12 '15394':7 '2025':10 '2...,2026-01-05,EDP ES,28152650000171,15394,GUACUI,FEC,2025,"8,00"
30,245333,'-01':2 '-05':3 '00':12 '11':11 '15394':7 '202...,2026-01-05,EDP ES,28152650000171,15394,GUACUI,DEC,2025,"11,00"

# Tratamento de Dados

In [ ]:
# Converte a coluna para número (trocando vírgula por ponto se necessário)
df_dec_realizado['VlrIndiceEnviado'] = pd.to_numeric(
    df_dec_realizado['VlrIndiceEnviado']
    .astype(str)
    .str.replace(',', '.', regex=False),
    errors='coerce',
)

df_dec_limite['VlrLimite'] = pd.to_numeric(
    df_dec_limite['VlrLimite'].astype(str).str.replace(',', '.', regex=False),
    errors='coerce',
)

In [ ]:
df_dec_realizado_filtro1 = df_dec_realizado[
    df_dec_realizado['SigIndicador'] == 'DEC'
]

# Agrupamento DEC REALIZADO
df_dec_realizado_agrupado = (
    df_dec_realizado_filtro1
    .groupby(
        ['IdeConjUndConsumidoras', 'DscConjUndConsumidoras'], as_index=False
    )['VlrIndiceEnviado']
    .sum()
    .sort_values('VlrIndiceEnviado', ascending=False)
)
df_dec_realizado_agrupado

  IdeConjUndConsumidoras DscConjUndConsumidoras  VlrIndiceEnviado
0                  15394                 GUACUI             49.65

In [ ]:
df_dec_limite_filtro1 = df_dec_limite[df_dec_limite['SigIndicador'] == 'DEC']

# Agrupamento DEC LIMITE
df_dec_limite_agrupado = (
    df_dec_limite_filtro1
    .groupby(
        ['IdeConjUndConsumidoras', 'DscConjUndConsumidoras'], as_index=False
    )['VlrLimite']
    .sum()
    .sort_values('VlrLimite', ascending=False)
)

df_dec_limite_agrupado

  IdeConjUndConsumidoras DscConjUndConsumidoras  VlrLimite
0                  15394                 GUACUI      192.0

# Resultado

In [ ]:
df_resultado = pd.merge(
    df_dec_realizado_agrupado,
    df_dec_limite_agrupado,
    on='IdeConjUndConsumidoras',
)
df_resultado

# Remover coluna
df_resultado = df_resultado.drop(columns=['DscConjUndConsumidoras_y'])

df_resultado_renomeado = df_resultado.rename(
    columns={
        'DscConjUndConsumidoras_x': 'Conjunto Elétrico',
        'VlrIndiceEnviado': 'DEC_Realizado',
        'VlrLimite': 'DEC_Limite',
    }
)

df_resultado_renomeado

  IdeConjUndConsumidoras Conjunto Elétrico  DEC_Realizado  DEC_Limite
0                  15394            GUACUI          49.65       192.0